name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NPM
        uses: npm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get npm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(npm store path --silent)" >> $GITHUB_ENV
  
      - uses: actions/cache@v3
        name: Setup npm cache
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api-two.vercel.app"
        with:
          build: npm run build
          start: npm start