name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get npm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(npm store path --silent)" >> $GITHUB_ENV
  
      - uses: actions/cache@v2
        name: Setup npm cache
        with:
          path: /home/carolinux/personal/rocketseat/ignite/reactjs/devstore 
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
        env: 
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api-two.vercel.app"